name: Pull Request Test

on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
  
      - name: Build
        shell: pwsh
        run: |
          CI/GitHubBuild.ps1
      
      - name: Run Core Test
        shell: pwsh
        run: |
          out/build/Release/Release/FBX-glTF-conv-core-test.exe

      - name: Run CLI Test
        shell: pwsh
        run: |
          out/build/Release/Release/FBX-glTF-conv-test.exe

  test_on_mac:
    name: Test on macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        name: Checkout
  
      - name: Build
        shell: pwsh
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.3.1.app
          CI/GitHubBuild.ps1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-files
          path: out/install/**/*

  test_on_min_supported_mac:
     name: Test on Min Supported macOS
     runs-on: macos-11
     needs: test_on_mac
     steps:
       - name: Download Artifacts
         uses: actions/download-artifact@v3
         with:
           name: macos-files
           path: out
       - name: Run Tests
         shell: pwsh
         run: |
           ls out
           chmod 777 ./out/Release/bin/FBX-glTF-conv
           ./out/Release/bin/FBX-glTF-conv

  test_on_ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
  
      - name: Build
        shell: pwsh
        run: |
          CI/GitHubBuild.ps1

